# Generated by Django 6.0.6 on 2026-06-19 06:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('escrow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputSupplyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('input_category', models.CharField(choices=[('seed', 'Seed'), ('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide'), ('irrigation', 'Irrigation'), ('labour', 'Labour')], max_length=50)),
                ('item_description', models.CharField(blank=True, max_length=300)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('afo_cap_at_time', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], db_index=True, default='pending', max_length=25)),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_requests', to='escrow.escrowwallet')),
                ('shopkeeper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_requests', to='accounts.shopkeeperprofile')),
            ],
            options={
                'db_table': 'input_supply_requests',
                'indexes': [models.Index(fields=['escrow', 'input_category'], name='input_suppl_escrow__98c3ca_idx'), models.Index(fields=['shopkeeper', 'status'], name='input_suppl_shopkee_393893_idx'), models.Index(fields=['status'], name='input_suppl_status_315810_idx')],
            },
        ),
    ]
