# Generated by Django 6.0.6 on 2026-06-17 06:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parcel_ref', models.CharField(max_length=100, unique=True)),
                ('district', models.CharField(db_index=True, max_length=110)),
                ('tehsil', models.CharField(blank=True, max_length=110)),
                ('total_acres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arazi_verified', models.BooleanField(default=True)),
                ('landowner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='accounts.landownerprofile')),
            ],
            options={
                'db_table': 'land',
            },
        ),
        migrations.CreateModel(
            name='TenantAgreement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agreement_type', models.CharField(choices=[('theka', 'Theka'), ('batai', 'Batai')], max_length=10)),
                ('leased_acres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('season', models.CharField(max_length=30)),
                ('theka_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('farmer_share_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('landowner_share_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('landowner_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='land.land')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_agreements', to='accounts.farmerprofile')),
            ],
            options={
                'db_table': 'tenant_agreements',
            },
        ),
        migrations.AddIndex(
            model_name='land',
            index=models.Index(fields=['district'], name='land_distric_683608_idx'),
        ),
        migrations.AddIndex(
            model_name='land',
            index=models.Index(fields=['landowner'], name='land_landown_1d3aac_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantagreement',
            index=models.Index(fields=['tenant', 'status'], name='tenant_agre_tenant__b2f7e5_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantagreement',
            index=models.Index(fields=['parcel', 'season'], name='tenant_agre_parcel__0a5e31_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantagreement',
            unique_together={('tenant', 'parcel', 'season')},
        ),
    ]
