# Generated by Django 6.0.6 on 2026-07-13 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_type', models.CharField(choices=[('loan_approved', 'Loan Approved'), ('loan_rejected', 'Loan Rejected'), ('loan_disbursed', 'Loan Disbursed'), ('escrow_phase_unlocked', 'Escrow Phase Unlocked'), ('agreement_approved', 'Tenant Agreement Approved'), ('agreement_rejected', 'Tenant Agreement Rejected'), ('input_payment_success', 'Input Payment Successful'), ('payment_received', 'Payment Received'), ('settlement_complete', 'Settlement Complete'), ('factory_settlement_confirmed', 'Factory Settlement Confirmed'), ('claim_filed', 'Insurance Claim Filed'), ('claim_reviewed', 'Insurance Claim Reviewed')], db_index=True, max_length=50)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('stubbed', 'Stubbed — SMS gateway pending')], db_index=True, default='stubbed', max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_08ab02_idx'), models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_f0aafd_idx')],
            },
        ),
    ]
