# Generated by Django 6.0.6 on 2026-07-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('loan_approved', 'Loan Approved'), ('loan_rejected', 'Loan Rejected'), ('loan_disbursed', 'Loan Disbursed'), ('escrow_phase_unlocked', 'Escrow Phase Unlocked'), ('agreement_approved', 'Tenant Agreement Approved'), ('agreement_rejected', 'Tenant Agreement Rejected'), ('input_payment_success', 'Input Payment Successful'), ('payment_received', 'Payment Received'), ('settlement_complete', 'Settlement Complete'), ('factory_settlement_confirmed', 'Factory Settlement Confirmed'), ('claim_filed', 'Insurance Claim Filed'), ('claim_reviewed', 'Insurance Claim Reviewed'), ('verification_request_received', 'Verification Request Received'), ('numberdar_approved', 'Numberdar Approved'), ('numberdar_rejected', 'Numberdar Rejected'), ('verification_escalated', 'Verification Escalated'), ('credit_otp_sent', 'Credit OTP Sent'), ('credit_check_completed', 'Credit Check Completed'), ('credit_check_manual_review', 'Credit Check Manual Review')], db_index=True, max_length=50),
        ),
    ]
