# Generated by Django 6.0.6 on 2026-07-14 19:04

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_user_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberdarProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jurisdiction_district', models.CharField(blank=True, db_index=True, default='', max_length=130)),
                ('jurisdiction_villages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), blank=True, default=list)),
                ('cnic_verified', models.BooleanField(default=False)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('total_farmers_verified', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numberdars_authorized', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='numberdar_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'numberdar_profiles',
            },
        ),
        migrations.CreateModel(
            name='FarmerVerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], db_index=True, default='pending', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('numberdar_notes', models.TextField(blank=True)),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_verifications', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_requests', to='accounts.farmerprofile')),
                ('numberdar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_requests', to='community.numberdarprofile')),
            ],
            options={
                'db_table': 'farmer_verification_requests',
            },
        ),
        migrations.AddIndex(
            model_name='numberdarprofile',
            index=models.Index(fields=['jurisdiction_district', 'is_active'], name='numberdar_p_jurisdi_b5252c_idx'),
        ),
        migrations.AddIndex(
            model_name='farmerverificationrequest',
            index=models.Index(fields=['numberdar', 'status'], name='farmer_veri_numberd_ee1354_idx'),
        ),
        migrations.AddIndex(
            model_name='farmerverificationrequest',
            index=models.Index(fields=['farmer', 'status'], name='farmer_veri_farmer__4dc76b_idx'),
        ),
    ]
