# Generated by Django 6.0.6 on 2026-06-18 12:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_funded', models.DecimalField(decimal_places=2, max_digits=14)),
                ('insurance_premium_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_spent_on_inputs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='escrow', to='loans.loanapplication')),
            ],
            options={
                'db_table': 'escrow_wallets',
            },
        ),
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('txn_type', models.CharField(choices=[('insurance', 'Insurance'), ('input', 'Input')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('input_category', models.CharField(blank=True, max_length=30)),
                ('afo_cap_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_escrow_transactions', to=settings.AUTH_USER_MODEL)),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='escrow.escrowwallet')),
            ],
            options={
                'db_table': 'escrow_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['escrow', 'txn_type'], name='escrow_tran_escrow__b9fae6_idx'), models.Index(fields=['escrow', 'input_category'], name='escrow_tran_escrow__be8d11_idx')],
            },
        ),
        migrations.CreateModel(
            name='EscrowMilestoneUnlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unlocked_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crops.croplifecyclemilestone')),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='escrow.escrowwallet')),
            ],
            options={
                'db_table': 'escrow_milestone_unlocks',
                'unique_together': {('escrow', 'milestone')},
            },
        ),
    ]
