# Generated by Django 6.0.6 on 2026-06-20 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('wallet_type', models.CharField(choices=[('farmer', 'Farmer'), ('landowner', 'Landowner'), ('shopkeeper', 'Shopkeeper'), ('platform', 'Platform'), ('bank', 'Bank'), ('bank_clearing', 'Bank Clearing')], db_index=True, max_length=25)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('direction', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=6)),
                ('txn_type', models.CharField(choices=[('input', 'Input'), ('profit', 'Profit'), ('fee', 'Fee'), ('theka', 'Theka'), ('batai', 'Batai'), ('insurance', 'Insurance'), ('settlement', 'Settlement')], db_index=True, max_length=30)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'db_table': 'wallet_transactions',
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['wallet_type'], name='wallets_wallet__18a09d_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='wallet_tran_wallet__3d47ad_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['txn_type'], name='wallet_tran_txn_typ_36183e_idx'),
        ),
    ]
