# Generated by Django 6.0.6 on 2026-07-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_wallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='txn_type',
            field=models.CharField(choices=[('input', 'Input'), ('profit', 'Profit'), ('fee', 'Fee'), ('theka', 'Theka'), ('batai', 'Batai'), ('insurance', 'Insurance'), ('settlement', 'Settlement'), ('farmer_profit', 'Farmer Profit'), ('batai_split', 'Batai Split'), ('theka_payment', 'Theka Payment'), ('platform_fee', 'Platform Fee')], db_index=True, max_length=30),
        ),
    ]
