# Generated by Django 6.0.6 on 2026-06-17 20:52

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=35, unique=True)),
                ('season', models.CharField(choices=[('rabi', 'Rabi'), ('kharif', 'Kharif')], max_length=35)),
            ],
            options={
                'db_table': 'crop_types',
            },
        ),
        migrations.CreateModel(
            name='CropLifecycleMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phase_number', models.PositiveSmallIntegerField()),
                ('phase_name', models.CharField(max_length=150)),
                ('day_offset', models.PositiveIntegerField()),
                ('unlock_pct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowed_input_categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40))),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestones', to='crops.croptype')),
            ],
            options={
                'db_table': 'crop_lifecycle_milestones',
                'ordering': ['phase_number'],
                'unique_together': {('crop', 'phase_number')},
            },
        ),
        migrations.CreateModel(
            name='CropInputCap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.CharField(max_length=130)),
                ('input_category', models.CharField(choices=[('seed', 'Seed'), ('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide'), ('irrigation', 'Irrigation'), ('labour', 'Labour')], max_length=40)),
                ('max_cost_per_acre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_season', models.CharField(max_length=40)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_caps', to='crops.croptype')),
            ],
            options={
                'db_table': 'crop_input_caps',
                'indexes': [models.Index(fields=['crop', 'district'], name='crop_input__crop_id_b55f83_idx'), models.Index(fields=['input_category'], name='crop_input__input_c_dbf57b_idx')],
                'unique_together': {('crop', 'district', 'input_category', 'valid_season')},
            },
        ),
    ]
