# Generated by Django 6.0.6 on 2026-06-18 06:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('crops', '0001_initial'),
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('acres_applied_for', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('interest_rate_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('bank_approved', 'Bank Approved'), ('disbursed', 'Disbursed'), ('repaid', 'Fully Repaid'), ('rejected', 'Rejected')], default='submitted', max_length=30)),
                ('rejection_reason', models.TextField(blank=True)),
                ('loan_recovered_to_date', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='accounts.bankprofile')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='crops.croptype')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='accounts.farmerprofile')),
                ('tenant_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='land.tenantagreement')),
            ],
            options={
                'db_table': 'loan_applications',
                'indexes': [models.Index(fields=['farmer', 'status'], name='loan_applic_farmer__3d16d6_idx'), models.Index(fields=['bank', 'status'], name='loan_applic_bank_id_3eafd1_idx'), models.Index(fields=['status'], name='loan_applic_status_2fc934_idx')],
            },
        ),
    ]
