# Generated by Django 6.0.6 on 2026-07-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='numberdar_verified_at_application',
            field=models.BooleanField(default=False),
        ),
    ]
