# Generated by Django 6.0.6 on 2026-07-15 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
        ('loans', '0002_loanapplication_numberdar_verified_at_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='credit_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit.creditcheck'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='credit_check_status',
            field=models.CharField(choices=[('not_run', 'Not Run'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('manual_review', 'Manual Review')], default='not_run', max_length=30),
        ),
    ]
