# Generated by Django 6.0.6 on 2026-06-19 10:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('batch_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_payout', models.DecimalField(decimal_places=2, max_digits=14)),
                ('actual_payout', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('grade_received', models.CharField(blank=True, max_length=25)),
                ('grade_deduction_pct', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('grade_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('in_transit', 'In Transit'), ('received', 'Received'), ('grade_confirmed', 'Grade Confirmed'), ('payment_triggered', 'Payment Triggered')], db_index=True, default='in_transit', max_length=35)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('grade_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='contracts.farmercontractallocation')),
            ],
            options={
                'db_table': 'batch_deliveries',
                'indexes': [models.Index(fields=['allocation', 'status'], name='batch_deliv_allocat_1e1c80_idx'), models.Index(fields=['status'], name='batch_deliv_status_445865_idx')],
            },
        ),
    ]
