# Generated by Django 6.0.6 on 2026-07-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit_tier',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('low_risk', 'Low Risk'), ('medium_risk', 'Medium Risk'), ('high_risk', 'High Risk')], default='unverified', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='numberdar_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('smallholder', 'Smallholder Farmer'), ('tenant', 'Tenant Farmer'), ('landowner', 'Landowner'), ('shopkeeper', 'Shopkeeper'), ('bank', 'Bank Manager'), ('factory', 'Factory Buyer'), ('insurance', 'Insurance Agent'), ('afo', 'AFO Officer'), ('admin', 'Platform Admin'), ('numberdar', 'Numberdar')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'numberdar_verified', 'district'], name='users_role_44075c_idx'),
        ),
    ]
