# Generated by Django 6.0.6 on 2026-07-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_credit_tier_user_numberdar_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceprofile',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
