# Generated by Django 6.0.6 on 2026-07-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_insuranceprofile_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopkeeperprofile',
            name='ntn_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='ntn_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='secp_registration_number',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='user',
            name='secp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
