# Generated by Django 6.0.6 on 2026-07-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ur', 'Urdu')], default='ur', max_length=15),
        ),
    ]
