# Generated by Django 6.0.6 on 2026-07-15 08:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_user_email'),
        ('loans', '0002_loanapplication_numberdar_verified_at_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cnic_number', models.CharField(max_length=25)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('manual_review', 'Manual Review')], db_index=True, default='pending', max_length=25)),
                ('risk_tier', models.CharField(blank=True, choices=[('low_risk', 'Low Risk'), ('medium_risk', 'Medium Risk'), ('high_risk', 'High Risk'), ('unverified', 'Unverified')], max_length=25, null=True)),
                ('credit_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_outstanding_debt', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('default_history_flag', models.BooleanField(default=False)),
                ('active_micro_loans_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ecib_status', models.CharField(blank=True, choices=[('regular', 'Regular'), ('overdue', 'Overdue'), ('write_off', 'Write-Off'), ('none', 'None')], max_length=25, null=True)),
                ('max_approved_limit_pkr', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('is_eligible', models.BooleanField(blank=True, null=True)),
                ('bank_reference_id', models.CharField(blank=True, max_length=120)),
                ('bank_decision_notes', models.TextField(blank=True)),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('otp_reference', models.UUIDField(blank=True, null=True)),
                ('raw_bank_response', models.JSONField(blank=True, null=True)),
                ('request_payload_hash', models.CharField(blank=True, max_length=68)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_checks', to='accounts.farmerprofile')),
                ('loan_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_checks', to='loans.loanapplication')),
            ],
            options={
                'db_table': 'credit_checks',
                'indexes': [models.Index(fields=['farmer', 'status'], name='credit_chec_farmer__92191d_idx'), models.Index(fields=['loan_application'], name='credit_chec_loan_ap_18ce9c_idx'), models.Index(fields=['requested_at'], name='credit_chec_request_9680ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='OTPConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('purpose', models.CharField(choices=[('credit_check', 'Credit Check')], default='credit_check', max_length=40)),
                ('phone_sent_to', models.CharField(max_length=35)),
                ('otp_hash', models.CharField(max_length=125)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='otp_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otp_consents',
                'indexes': [models.Index(fields=['user', 'purpose', 'verified'], name='otp_consent_user_id_527ba7_idx')],
            },
        ),
    ]
