# Generated by Django 6.0.6 on 2026-06-19 20:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('land', '0001_initial'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gross_payout', models.DecimalField(decimal_places=2, max_digits=14)),
                ('proportional_principal_deduction', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bank_interest_deduction', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bank_factoring_commission', models.DecimalField(decimal_places=2, max_digits=14)),
                ('platform_transaction_fee', models.DecimalField(decimal_places=2, max_digits=14)),
                ('theka_payment', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('batai_landowner_share', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('farmer_net_profit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('insurance_claim_triggered', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('advanced', 'Advanced'), ('factsettl', 'FactSettl'), ('complete', 'Complete')], db_index=True, default='pending', max_length=25)),
                ('bank_advanced_at', models.DateTimeField(blank=True, null=True)),
                ('factory_paid_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='delivery.batchdelivery')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='loans.loanapplication')),
                ('tenant_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='land.tenantagreement')),
            ],
            options={
                'db_table': 'settlement_invoices',
                'indexes': [models.Index(fields=['loan', 'status'], name='settlement__loan_id_ca3811_idx'), models.Index(fields=['status'], name='settlement__status_f0d40a_idx')],
            },
        ),
    ]
