# Generated by Django 6.0.6 on 2026-06-19 04:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('claimed', 'Claimed'), ('expired', 'Expired')], db_index=True, default='active', max_length=25)),
                ('policy_start', models.DateField()),
                ('policy_end', models.DateField()),
                ('insurer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='accounts.insuranceprofile')),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_policy', to='loans.loanapplication')),
            ],
            options={
                'db_table': 'insurance_policies',
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField()),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewer_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_claims', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='insurance.insurancepolicy')),
            ],
            options={
                'db_table': 'insurance_claims',
            },
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['status'], name='insurance_p_status_080899_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(fields=['policy', 'status'], name='insurance_c_policy__a6ac3f_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(fields=['claimed_by', 'status'], name='insurance_c_claimed_189c04_idx'),
        ),
    ]
