# Generated by Django 6.0.6 on 2026-06-19 09:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('crops', '0001_initial'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('required_kg', models.DecimalField(decimal_places=2, max_digits=16)),
                ('allocated_kg', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('base_price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_defer_days', models.PositiveSmallIntegerField(default=20)),
                ('quality_grade_expected', models.CharField(default='Grade A', max_length=25)),
                ('status', models.CharField(choices=[('open', 'Open'), ('allocated', 'Allocated'), ('completed', 'Completed')], db_index=True, default='open', max_length=30)),
                ('delivery_deadline', models.DateField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='crops.croptype')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='accounts.factoryprofile')),
            ],
            options={
                'db_table': 'crop_contracts',
            },
        ),
        migrations.CreateModel(
            name='FarmerContractAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('committed_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='contracts.cropcontract')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_allocations', to='accounts.farmerprofile')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_allocations', to='loans.loanapplication')),
            ],
            options={
                'db_table': 'farmer_contract_allocations',
            },
        ),
        migrations.AddIndex(
            model_name='cropcontract',
            index=models.Index(fields=['crop', 'status'], name='crop_contra_crop_id_31c10d_idx'),
        ),
        migrations.AddIndex(
            model_name='cropcontract',
            index=models.Index(fields=['factory', 'status'], name='crop_contra_factory_858e89_idx'),
        ),
        migrations.AddIndex(
            model_name='farmercontractallocation',
            index=models.Index(fields=['contract', 'farmer'], name='farmer_cont_contrac_0eedf6_idx'),
        ),
        migrations.AddIndex(
            model_name='farmercontractallocation',
            index=models.Index(fields=['farmer'], name='farmer_cont_farmer__112f3b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='farmercontractallocation',
            unique_together={('contract', 'farmer')},
        ),
    ]
